Render vaccination_centres.
gravitystorm/openstreetmap-carto pull request #4300
Opened 2021-01-27 14:38 UTC by StyXman

Fixes #4295.

Changes proposed in this pull request:
- add `healtcare=vaccination_centre`

Test rendering with links to the example places:

https://www.openstreetmap.org/#map=15/51.5566/-0.2794

Before
![Screenshot_20210127_153709](https://user-images.githubusercontent.com/167327/106006483-903a0280-60b5-11eb-8905-f35855196976.png)

After:
![Screenshot_20210127_153623](https://user-images.githubusercontent.com/167327/106006394-7698bb00-60b5-11eb-935f-86382cd57c77.png)

The `vaccination_centre` is just north of the Wembley Stadium.

2021-01-27 14:39 UTC, StyXman commented
The icon is a 10px hospital one, as I couldn't find any that looked like a syringe :)

2021-01-27 15:37 UTC, polarbearing commented
We cannot re-use the hospital icon while telling mappers not to tag the vacc-centres as hospital. 
Works neither cartographically nor as mapper feedback. 
Icons usually have to be created, not found.

2021-01-27 16:24 UTC, imagico commented
Thanks for the submission - code looks fine, although i have not tested it.

Right now i see the following problems with this:

* Use of the tag is not very widespread so far - about a hundred compared to >500 for healthcare:speciality=vaccination.  We should not push for a newly created tag and instead wait until it is clear if said tag finds broad support from the community (which is likely here but not guaranteed).
* Many of the places tagged with this seem not open to the general public but only accessible with an appointment you get subject to varying conditions.  So far however taggings indicating such things are not widely used.  Indiscriminately showing  vaccination centers without indicating if these are open to the general public would limit usefulness of rendering to the map user.
* A distinct and intuitively readable symbol is an absolute necessity for adding rendering.  If a smaller version of an existing symbol is used (and i don't think that is a good idea here) it would need to be adjusted to good quality rendering at the target size.
* As with other POI rendering suggestions an overall concept of symbology in the domain in question (here: medical/healthcare facilities) that the symbol fits in here should be a prerequisite.  At hoc, compartmentalized additions of individual symbols are not a good idea - see #3635.  In this case specifically the question that would need to be considered is should we decide to render vaccination centers if we should also render vaccination opportunities at places other than dedicated vaccination centers (i.e. healthcare:speciality=vaccination or vaccination=* as addon tags for other medical facilities).  Not doing so could very well create counterproductive mapping incentives (i.e. people adding healtcare=vaccination_centre to indicate a vaccination opportunity that is not a dedicated vaccination center).

2021-01-27 16:41 UTC, StyXman commented
This tag has been approved recently: https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:healthcare%3Dvaccination_centre

> Use of the tag is not very widespread so far - about a hundred compared to >500 for healthcare:speciality=vaccination

Let's use that one too, then.

> Many of the places tagged with this seem not open to the general public but only accessible with an appointment you get subject to varying conditions. So far however taggings indicating such things are not widely used. Indiscriminately showing vaccination centers without indicating if these are open to the general public would limit usefulness of rendering to the map user.

Let's narrow down the filters then. Any suggestions?

> A distinct and intuitively readable symbol is an absolute necessity

Yeah, I put the hospital icon just to prove the SQL query works. Does anyone know a syringe icon somewhere? I _will_ try to find one myself, but my time is quite limited.

2021-01-27 18:33 UTC, polarbearing commented
It's unlikely to _find_ an icon matching the requirements here, which is a 14px-optimised monochrome svg.
I'd imagine a syrringe can be drawn as a T for the handle, a rectangle and a thin line, diagonally. Will see if I find time to try.

2021-01-29 05:32 UTC, jeisenbe commented
While I was personally involved in creating this tag, I don’t think it is well established enough to render right now, considering that we don’t render more common tags like healthcare=laboratory. 

However, it would be worth considering adding rendering along with a few of the most common healthcare=* tags once it is more common - see https://wiki.openstreetmap.org/wiki/Template:Map_Features:healthcare

Perhaps we coudl use a generic, abstract icon such as a filled circle, rather than creating new icons for each feature? 

See also #3635 for discussion about the abundance of icons in this style.

2021-01-31 21:37 UTC, jeisenbe requested changes
This PR currently would not render the names of healthcare=vaccination_centre features. That would require adding this to line 2552: https://github.com/gravitystorm/openstreetmap-carto/blob/d13ed55f5ea4a1ae3e263bce0622baad1a80b5cf/style/amenity-points.mss#L2552 - and as mentioned the icon needs to be changed

2021-01-31 21:37 UTC, jeisenbe commented on style/amenity-points.mss
> +    marker-file: url('symbols/amenity/hospital.svg');
The symbol needs to be changed, as discussed, either to a generic icon which can be used for a number of healthcare features which are currently not yet rendered (e.g. laboratories, test centres, birth centres, midwives, nurses, chiropractors, acupuncture, etc) or a unique symbol needs to be created which is recognizable, e.g. a syringe.

2021-06-25 23:45 UTC, enzet commented
Here are some sketches of 14 × 14 px icon:

![syringe_1](https://user-images.githubusercontent.com/2399987/123494330-2011b780-d628-11eb-9601-57c60c1c5ad6.png)

The same × 4:

![syringe_4](https://user-images.githubusercontent.com/2399987/123494333-20aa4e00-d628-11eb-80b4-fc66421b8da0.png)

Any thoughts? What is better: more detailed, more pixel-perfect?

2021-06-26 09:27 UTC, imagico commented
Those look very good.  The other issues mentioned in https://github.com/gravitystorm/openstreetmap-carto/pull/4300#issuecomment-768402991 still apply of course.  Considering as mentioned vaccination opportunities are often tagged with addon tags (healthcare:speciality=vaccination, vaccination=*) to various medical facilities it could be worth trying to indicate this with symbol variations (i.e. adding a syringe symbol to existing symbols for doctors/clinics etc.)  I am not saying that this would necessarily work well in this style but it could be worth trying out (also potentially for other medical specialities of course).

2021-06-26 10:23 UTC, enzet commented
> it could be worth trying to indicate this with symbol variations (i.e. adding a syringe symbol to existing symbols for doctors/clinics etc.)

Sorry, not sure I got you right. Do you mean something like that?

![syringe_cross](https://user-images.githubusercontent.com/2399987/123509994-94c51000-d681-11eb-8bf6-d93011d860f2.png)

2021-06-26 10:28 UTC, pnorman commented
Scaled to 8x
![image](https://user-images.githubusercontent.com/1190866/123510043-22771000-d62e-11eb-89ad-f8b786a70450.png)
Numbering from the top-left and going across, the first three should all have a one pixel gap like the ones below. 
Four and eight are quite blurry because they're angled.

2021-06-26 11:31 UTC, enzet commented
> the first three should all have a one pixel gap like the ones below

I've intentionally added half-pixel gaps to some icons and one-pixel gaps to others to compare and select the best elements.

2021-06-26 11:40 UTC, imagico commented
> Sorry, not sure I got you right. Do you mean something like that?

In principle yes.  But that is delicate work to design with non-misleading semantics.  It would need to be clear that the added syringe indicates a subtype of the symbol without it.  We have something like that for different kinds of parking ('P' symbol plus additional symbol) but this would be more difficult for healthcare symbols, in particular because of #3613 and because current healthcare symbols here use a Swiss coat of arms/negative space symbol rather than an actual red cross.

2021-06-26 20:58 UTC, enzet commented
Well, I realized that the syringe shape wasn't right. I also changed the needle shape. There are updated and rearranged sketches:

![syringe_2](https://user-images.githubusercontent.com/2399987/123525512-e0a3a380-d6d9-11eb-94a3-ab2fbce637e0.png)

× 4:

![syringe_2_x4](https://user-images.githubusercontent.com/2399987/123525514-e7321b00-d6d9-11eb-908a-ecfb575b1dde.png)

For references:
  * without gaps: 2.1 — 2.4,
  * with half-pixel gaps: 2.5 — 2.8,
  * with one-pixel gaps: 2.9 — 2.12.

So far I prefer 2.2 cause it's the most recognizable one.

2022-06-06 07:00 UTC, jeisenbe commented
@StyXman could you update this PR with the new symbol and address the previous comment about line 2552?

Now used 700 times, probably not going away anytime soon.

2022-06-28 05:28 UTC, pnorman commented
Closing as stale. If you're still interested in this, feel free to open a new PR addressing the above comments.

2022-06-28 05:28 UTC, closed without merging