Add rendering for `highway=busway`
gravitystorm/openstreetmap-carto pull request #4385
Opened 2021-04-23 04:07 UTC by kolgza

This is basically the same pull request as #4382, except from a different branch. In other words, I don't know how to use git. @imagico: please request the same changes as before.

---

### Fixes # (id of the issue to be closed)
- #4226

### Changes proposed in this pull request:
The rendering for `higway=bus_guideway` would be applied to instances of `highway=busway`.

### Test rendering with links to the example places:
- https://www.openstreetmap.org/relation/4051402#map=15/40.4294/-80.0636

#### Before
![image](https://user-images.githubusercontent.com/46303203/115767526-43458f80-a377-11eb-831b-99395b138b71.png)

### After
![image](https://user-images.githubusercontent.com/46303203/115767409-1db88600-a377-11eb-9440-ac68c599115a.png)

2021-04-23 12:12 UTC, imagico requested changes
See comments on #4382.

I am not opposed to the idea of rendering bus only roads built and used for specific bus routes in a distinct fashion.  But i don't think the tag highway=busway has shown clear enough adoption and consistency in use by mappers to support rendering it here and i don't think the suggested rendering (in particular the blue color) is a good choice for that - in particular also where these roads connect to the general road network.  That is different for bus_guideway - which is more rail like and does not transit to regular roads.

2021-04-23 14:07 UTC, kolgza commented
> i don't think the suggested rendering (in particular the blue color) is a good choice for that

This relates to  #3396

2021-04-23 16:56 UTC, kolgza commented
> That is different for bus_guideway - which […] does not transition to regular roads.

Here is a counterexample:
![image](https://user-images.githubusercontent.com/46303203/115903590-c3c8c680-a431-11eb-916a-0f26cb0ae595.png)
![image](https://user-images.githubusercontent.com/46303203/115903609-c7f4e400-a431-11eb-8038-f102c0e66b22.png)

This issue is inherent to the fact that `highway=bus_guideway` is rendered like a railway, but must somehow merge into roads.
@pnorman discussed both redoing the rendering for bus guideways, and unifying it with `highway=busway`.

2021-04-25 16:31 UTC, kolgza commented
@imagico Would you merge this PR if it instead applied the rendering of `highway=service` to `highway=busway`?

2021-04-26 10:30 UTC, imagico commented
Also keep in mind #3581 - the rendering of `highway=bus_guideway` currently suffers from various issues related to layering relative to other roads features.  It would not be advisable to extend this highly suboptimal rendering to additional features without addressing those issues first.

2021-04-26 21:05 UTC, kolgza commented
Closing, because I lack the expertise to implement this.

2021-04-26 21:05 UTC, closed without merging