water: render waterway=fish_pass
gravitystorm/openstreetmap-carto pull request #4388
Opened 2021-04-25 17:07 UTC by TheJJ

Fixes #2895

Changes proposed in this pull request:
- Render `waterway=fish_pass`

I don't have tested this at all and I still need to figure out how to produce a test rendering :)

2021-04-26 10:54 UTC, HolgerJeromin commented
At least 
https://github.com/gravitystorm/openstreetmap-carto/blob/42a6baf41a6e8f7020ff005a18e2f63e75a97d1b/project.mml#L180
and line 220 (and others) seems to be missing.

2021-04-26 12:41 UTC, imagico commented
Thanks for the PR.  We generally require PRs to be tested and examples of before and after rendering to be shown to allow a quick assessment of what the change tries to achieve.  This does not necessarily have to be done by the person submitting the PR of course.  When you implement a change with visual impact on the rendering it is generally highly advisable to visually check the results.

2021-04-26 13:14 UTC, TheJJ commented
Definitely :smile: I just wanted to get the ball rolling.
What would be the simplest possible way to test the changes? Apart from of course somebody with the setup in place creating the renders.

2021-09-11 18:49 UTC, pitdicker commented on style/water.mss
> +      [waterway = 'fish_pass'][zoom >= 15] {
Can you merge this section with the one above for `[waterway = 'stream'][zoom >= 15]`?

2021-09-11 18:51 UTC, pitdicker reviewed
Looks good to me.

Before (https://www.openstreetmap.org/#map=18/52.49547/6.58054):
![before](https://user-images.githubusercontent.com/6255050/132958340-22ee20b8-f80f-4894-bfd3-5d8069199752.png)

After:
![after](https://user-images.githubusercontent.com/6255050/132958352-7c8aa641-53e9-4599-89e5-87f03e84d229.png)

2021-09-11 18:51 UTC, pitdicker commented on style/water.mss
> +      [waterway = 'fish_pass'][zoom >= 15] {
Can you merge this section with the one above for `[waterway = 'stream'][zoom >= 15]`?

2021-09-11 18:51 UTC, pitdicker commented on style/water.mss
> +        [waterway = 'fish_pass'] {
Can you merge this section with the one above for `[waterway = 'stream']`

2022-05-07 17:33 UTC, TheJJ commented
bump bamp, what is remaining to bring this upstream?

2022-06-06 07:02 UTC, jeisenbe commented
It looks like @pitdicker approved this in a prior review. Does anyone else have time to test this?

2022-06-06 13:35 UTC, imagico requested changes
This seems to work as intended.

As long as we render waterway=stream and waterway=ditch/drain differently (see #2346) i think it would be more logical to have waterway=fish_pass match the rendering of waterway=ditch/drain and not waterway=stream.

Apart from that i think this is something we can add, i am just somewhat wondering if it would be better to render waterway=fish_pass like waterway bridges rather than like a plain waterway.  This would make fish passes in the middle of a river across a weir for example visible.  Like:

https://www.openstreetmap.org/way/714071249
https://www.openstreetmap.org/way/466865795
https://www.openstreetmap.org/way/993880729
https://www.openstreetmap.org/way/285989535

I am not sure about this given the different styles in mapping that exist (see https://github.com/gravitystorm/openstreetmap-carto/issues/2895#issuecomment-1147438074) - so just a thought, not a request for changes.

2023-02-08 15:01 UTC, TheJJ commented
rebased. somebody with a working setup please test :)

2023-11-10 14:30 UTC, imagico commented
Setting this as draft.  It requires

* changing rendering of `waterway=fish_pass` to match that of `waterway=ditch`/`waterway=drain` rather than `waterway=stream` as it does at the moment (or alternatively: fixing #2346).
* practical testing and samples.
* optionally: evaluation if this would work better when rendered like a wayterway bridge rather than a normal waterway so fish passes within a riverbank polygon (for example across a weir) are visible.

2026-06-19 21:11 UTC, closed without merging