Add phantom labels for all bridges
gravitystorm/openstreetmap-carto pull request #4426
Opened 2021-06-21 10:38 UTC by alfmarcua

**Partially fixes #478** 

**Changes proposed in this pull request:**
- Add a phantom label to all bridges in order to displace water labels for not to be on top of bridges

**Test rendering with links to the example places:**

Before:
![Selección_006](https://user-images.githubusercontent.com/25908318/122748812-e853ea00-d28c-11eb-8665-8f051fb91df8.png)

After:
![Selección_007](https://user-images.githubusercontent.com/25908318/122748834-eee26180-d28c-11eb-8df6-e06b805039d3.png)

2021-06-21 10:40 UTC, alfmarcua commented
It is just a partial humble solution. There are cases where the solution still does not apply, the bridge label itself shall be displayed but it is large enough. Hence, it is not displayed. Here it is an example:

Before:
![Selección_009](https://user-images.githubusercontent.com/25908318/122749576-cad35000-d28d-11eb-94ec-04084dbf3d22.png)

After:
![Selección_008](https://user-images.githubusercontent.com/25908318/122749564-c7d85f80-d28d-11eb-9a59-71abd60ec91b.png)

2021-06-21 10:51 UTC, pnorman commented
I think the bigger concern is roads that are bridges, not the man_made=bridge structure.

2021-06-21 14:58 UTC, imagico commented
Yes, this is nice to see as a proof of concept for using pro forma labels to influence label placement in mapnik (and the limitations of this) but this will not solve the core of #478 and furthermore the pro forma labels for unnamed bridges will also block labels of bridge=yes roads which would be highly confusing for mappers.

2021-06-22 06:51 UTC, alfmarcua commented
I might have some ideas for roads as well. I will try to update with an approach. Although, I think that the main problem of this solution is that there are labels which are not displayed due to surrounding elements.

2021-07-12 11:13 UTC, alfmarcua commented
In this new commit I have tried to overcome the issue regarding roads that are bridges. 

In particular, a new layer is created, roads-text-name-phantom, just before the roads labels layer (roads-text-name). This layer contains only roads that are bridges and that have their names not null. In brings a new field which I called char_per_pixel which represents the number of characters that are per pixel.

The idea is that if the number of characters per pixel is below a threshold, then the label will fit the bridge and it could be represented. Hence, in the style it is declared that a phantom label will be placed whenever the number of characters per pixel of a road's label is above that threshold.

Notice that this threshold is text size dependant, so that property should be taken into account. In fact, the property phantom-line-text-threshold has been estimated from testing the limit of text size for a certain label of a bridge to be displayed or not. The tests have been with several different bridges.

Here is a snashot of the difference in Kosmtik comparison view:
- Left: OpenStreetMap
- Right: latest implementations

![phantom-roads](https://user-images.githubusercontent.com/25908318/125278312-da850800-e312-11eb-84b1-c853e1598504.png)

2021-09-17 07:34 UTC, alfmarcua commented
@pnorman @imagico What do you think about this new approach? Did you have time to review it? 

It covers all bridges and it takes into account the size of the labels regarding the space they have in order to be represented.

2021-09-17 23:43 UTC, pnorman commented
I'd rather clean up the roads layers before adding any complexity around them,

2021-09-19 05:10 UTC, jeisenbe requested changes
@alfmarcua - thank you for trying to solve this problem. 

Unfortunately, as mentioned in the issue #478 there is no simple way to fix these sort of problems with automated label placement in Mapnik. Creating an additional layer, as done in this PR, will add complexity to the code, increase computational cost, and slow down rendering, for a small improvement in the rendering result.

2021-10-04 10:36 UTC, alfmarcua commented
Thank you for your comments. As you comment, it is a complex problem as the optimal solution requires a lot of effort. Hence, I close this pull request.

2021-10-04 10:36 UTC, closed without merging