only render addr:flats where value is 7 characters or less
gravitystorm/openstreetmap-carto pull request #4430
Opened 2021-06-26 11:19 UTC by andrewharvey

The vast majority of addr:flats values are 7 characters or less and this captures values like "101-909", however since significantly longer values are valid tags and do occur throughout OSM data, they are not rendered to prevent the map being overwhelmed by these labels, and to reduce temptation for people to delete these valid tags to "improve the map rendering".

Fixes #4160

2021-06-27 09:46 UTC, imagico commented
As said in https://github.com/gravitystorm/openstreetmap-carto/issues/4160#issuecomment-868987197 i don't think dropping labels exceeding a certain length is a good idea.  Confusion about the logic behind some labels showing up while others don't (due to collision and prioritization) is already one of the most frequent complaints of map users - despite the current mechanism being reasonably easy to understand.  Adding additional complexity to that by hiding some labels based on length despite there being enough space to show them would significantly add to that problem.

2021-06-27 14:06 UTC, pnorman requested changes
I'm okay with the idea of either not showing or cutting the labels short, but this PR won't do that reliably. If an object has addr:housenumber it will be included even if the addr:flats is > 7 characters.

2021-06-28 02:02 UTC, andrewharvey commented
I'll probably need to work out how to get this running locally to test it properly.

Personally I'm still leaning more towards dropping anything >7 chars than doing ..., but that's just my opinion.

2022-06-06 06:41 UTC, jeisenbe requested changes
A limit of 7 characters will cause a simple and valid tag such as `addr:flats=1001-1099` not to render. This would be confusing.

2022-06-06 06:46 UTC, andrewharvey commented
> A limit of 7 characters will cause a simple and valid tag such as addr:flats=1001-1099 not to render. This would be confusing.

I increased it to 9.

2022-06-20 00:58 UTC, pnorman requested changes
Some SQL changes.

I'm still not that convinced on the idea of restricting the length, but will defer to other maintainers there.

2022-06-20 00:58 UTC, pnorman commented on project.mml
> +            CASE char_length(tags->'addr:flats') <= 9 WHEN TRUE THEN tags->'addr:flats' ELSE NULL END AS addr_flats,
Don't use the switch-statement style case statement with an expression that evaluates to a boolean, instead do `CASE WHEN char_length(tags->'addr:flats') <= 9 THEN tags->'addr:flats' END AS addr_flats,`

2022-06-20 00:58 UTC, pnorman commented on project.mml
> +            CASE char_length(tags->'addr:flats') <= 9 WHEN TRUE THEN tags->'addr:flats' ELSE NULL END AS addr_flats,
Same as above for the switch-style case statement

2023-01-08 22:36 UTC, pnorman commented
There are unresolved technical issues with this PR. I also don't think any of the maintainers think dropping long addr:flats tags is a good idea.

2023-01-08 22:36 UTC, closed without merging