Allow file:// urls in the config file
gravitystorm/openstreetmap-carto pull request #4468
Opened 2021-09-14 19:00 UTC by stephan2012

Signed-off-by: Stephan Austermühle <au@hcsd.de>

Changes proposed in this pull request:

This small technical PR allows using `file://` urls in the config file (`.sources.*.url`) which is helpful for loading external data in air-gap environments, i.e., systems without Internet connection.

This workflow illustrates the need for the change:

1. Download external files (requires [yq](https://github.com/mikefarah/yq)):

    ```bash
    yq eval '.sources.*.url' external-data.yml |xargs -P4 -i curl -x "${https_proxy:-}" --silent --fail --output-dir external-data -LO {}
    ```

2. Replace external by file urls:

    ```bash
    yq -i eval '.sources.*.url |= sub("^https://.*/(.*)$", "file:///var/lib/openstreetmap-carto/external-data/${1}")' external-data.yml
    ```

3. `get-external-data.py` can now load the files locally

2021-09-15 21:29 UTC, pnorman requested changes
When everything is installed as per the documentation, you get this error
```
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 25, in <module>
    from requests_file import FileAdapter
ModuleNotFoundError: No module named 'requests_file'
```

The documentation needs updating. Additionally, I would prefer not to require an additional package in the common case where local files are not being used.

2021-09-15 21:30 UTC, pnorman commented
Both this and #4435 would accomplish the goals, correct? I'm not sure which is the better approach.

2021-09-16 06:16 UTC, stephan2012 commented
> Both this and #4435 would accomplish the goals, correct? I'm not sure which is the better approach.

@nmaludy and I implemented the same feature at the same time, so obviously there is a need for it. 😉

Agree, the documentation requires an update. Will add this unless someone decides for the other approach. Besides that, IMHO adding a package (`python3-requests-file`) is really nothing to worry about.

2022-06-05 15:03 UTC, pnorman requested changes
I haven't tested the technical changes yet - I need to get home to do that - but there's a minor documentation issue.

Otherwise, good with the approach.

2022-06-05 15:03 UTC, pnorman commented on INSTALL.md
> +* Python 3 with the psycopg2, yaml, and requests libraries (`python3-psycopg2`, `python3-yaml`, `python3-requests`, `python3-requests-file` packages on Debian-derived systems)
If we use commas, we need to specify "and". Personally, I slightly prefer without commas so you can copy and paste the package list

2022-06-20 00:24 UTC, merged