Potential fix for the issue of missing features in the 'planet_osm_transport_line' table
gravitystorm/openstreetmap-carto pull request #4492
Opened 2021-11-17 09:58 UTC by mboeringa

Potential fix for the issue raised here https://github.com/gravitystorm/openstreetmap-carto/pull/4431#pullrequestreview-806339969.

This adds code for adding back-in the highway / boundary double tagged features that apparently get deleted from the 'planet_osm_transport_line' when the 'planet_osm_admin' table is filled in stage 2 processing of osm2pgsql.

Fixes # (id of the issue to be closed)

Changes proposed in this pull request:
- 

Test rendering with links to the example places:

Before
https://user-images.githubusercontent.com/7635726/141824056-010887af-ef75-45fd-af35-5e1369334168.png
After
![afbeelding](https://user-images.githubusercontent.com/7635726/142178883-7c0524e1-729a-4cef-b462-ad727b092c5b.png)

2021-11-17 19:51 UTC, pnorman requested changes
Before I review this for correctness, can you please add tests. This will make it easier to review.

2021-11-17 20:28 UTC, mboeringa commented
> Before I review this for correctness, can you please add tests. This will make it easier to review.

To be honest, I have no idea how to do that. I have limited experience with GitHub. 

More general question though: is that even necessary? It is just three of your own code lines that I copied over from another function of the style into the "stage2" processing section of the "osm2pgsql.process_way()" function you wrote as well.

It seemed the logical thing to do based on the observed behavior of the issue as discussed in https://github.com/gravitystorm/openstreetmap-carto/pull/4431#pullrequestreview-806339969, where the "highway" road elements seemed to be deleted from  the 'planet_osm_transport_line' table once stage 2 processing of osm2pgsql kicks in.

The new code lines just add them back in a second time. I just don't know if this is the correct solution, or that the issue I discovered potential represent an osm2pgsql bug related to stage 2 processing.

2021-12-05 22:23 UTC, pnorman commented
Yes, tests are necessary. They verify the correctness of what you've done and prevent regressions in the future.

2021-12-22 08:57 UTC, pnorman commented
I have some code locally that fixes this, I just need to see why tests weren't catching it before and fix them. This code is different than what's in this PR - the PR isn't sufficient to fix all cases of this problem.

Diff without tests is
```diff
diff --git a/openstreetmap-carto.lua b/openstreetmap-carto.lua
index a0dbe4c2..55d5c3e9 100644
--- a/openstreetmap-carto.lua
+++ b/openstreetmap-carto.lua
@@ -664,34 +664,33 @@ function osm2pgsql.process_node(object)
 end

 function osm2pgsql.process_way(object)
-    if osm2pgsql.stage ==  1 then
-        if clean_tags(object.tags) then
-            return
+    if osm2pgsql.stage == 2 then
+        -- Stage two processing is called on ways that are part of admin boundary relations
+        local props = phase2_admin_ways[object.id]
+        if props ~= nil then
+            tables.admin:add_row({admin_level = props.level, multiple_relations = (props.parents > 1), geom = { create = 'line' }})
         end
+    end
+    if clean_tags(object.tags) then
+        return
+    end

-        local area_tags = isarea(object.tags)
-        if object.is_closed and area_tags then
-            add_polygon(object.tags)
-
-            if z_order(object.tags) ~= nil then
-                add_transport_polygon(object.tags)
-            end
-        else
-            add_line(object.tags)
+    local area_tags = isarea(object.tags)
+    if object.is_closed and area_tags then
+        add_polygon(object.tags)

-            if z_order(object.tags) ~= nil then
-                add_transport_line(object.tags)
-            end
+        if z_order(object.tags) ~= nil then
+            add_transport_polygon(object.tags)
+        end
+    else
+        add_line(object.tags)

-            if roads(object.tags) then
-                add_roads(object.tags)
-            end
+        if z_order(object.tags) ~= nil then
+            add_transport_line(object.tags)
         end
-    elseif osm2pgsql.stage == 2 then
-        -- Stage two processing is called on ways that are part of admin boundary relations
-        local props = phase2_admin_ways[object.id]
-        if props ~= nil then
-            tables.admin:add_row({admin_level = props.level, multiple_relations = (props.parents > 1), geom = { create = 'line' }})
+
+        if roads(object.tags) then
+            add_roads(object.tags)
         end
     end
 end
```

2021-12-22 08:57 UTC, closed without merging

2021-12-23 19:35 UTC, mboeringa commented
@pnorman 

I now tested the changes you suggested in the diff by copying over these changes of the diff to my own version of your style. I have some minor modifications in my style, but those are unrelated to this code.

First testing seems to indicate the changes you suggested are OK. The top image below shows the result of the modified style, where the roads double tagged as boundary, are correctly rendered. Compare that image with the one below it, that shows the original issue:

![afbeelding](https://user-images.githubusercontent.com/7635726/147284411-aa3cb86e-d380-42c9-a912-bbad578989d5.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/147284750-de740a5e-f9fd-487f-bb7f-b07629fff780.png)