update INSTALL.md with fonts-unifont package
gravitystorm/openstreetmap-carto pull request #4520
Opened 2022-03-02 09:42 UTC by andrewharvey

ttf-unifont is now fonts-unifont on recent Debian releases

Old: https://packages.debian.org/buster/all/ttf-unifont/filelist
Current: https://packages.debian.org/sid/all/fonts-unifont/filelist

2022-04-24 22:00 UTC, slachiewicz approved these changes

2022-04-25 18:19 UTC, pnorman commented
The line above talks about Ubuntu 16.04 - does that need updating too?

2022-04-26 00:05 UTC, andrewharvey commented
> The line above talks about Ubuntu 16.04 - does that need updating too?

Looks like in Ubuntu `fonts-unifont` became available in 21.04
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=fonts-unifont

and `ttf-unifont` is still available in 21.10
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=ttf-unifont

Are you happy to bump that Ubuntu 16.04 version to 21.04 and leave behind people on older versions of Ubuntu?

2022-04-26 17:15 UTC, pnorman commented
I think we need 20.04 support until 22.04 has been out longer, so this would mean two different font installation lines for different versions.

2022-06-05 15:00 UTC, pnorman requested changes
If different install instructions are needed for 20.04 and 22.04, I would go for lines like

> On Ubuntu N or Debian X you can...
> On Ubuntu M or Debian Y you can...

2022-07-28 05:53 UTC, pnorman commented
Closing as abandoned. As above, the instructions would need modification to support different versions.

2022-07-28 05:53 UTC, closed without merging