Fix shop=car_repair label/icon colour mismatch
gravitystorm/openstreetmap-carto pull request #4536
Opened 2022-04-21 18:29 UTC by jdhoek

The colour of the icon (purple) and the label (brown) don't match.

This commit makes the icon brown in line with other service providing
amenities.

Fixes #2658

-----

_This is one of two ways to solve this. The other colour choice is shown in #4535. These two PR's are mutually exclusive._

_Either one is probably better than:_ ![nope](https://user-images.githubusercontent.com/683699/164528484-f6b6ff94-59d9-45a2-b479-b0a8c6370cf9.png)

-----

# Before

![17-now](https://user-images.githubusercontent.com/683699/164527921-539fc130-f1fe-412f-9721-0be4cbfb266d.png)

![18-now](https://user-images.githubusercontent.com/683699/164527945-ee4069ab-bcf0-4665-8a6b-776443739c79.png)

# After

![17-brown](https://user-images.githubusercontent.com/683699/164528151-3331b3ca-2fac-420a-a945-dbf9b2b494ad.png)

![18-brown](https://user-images.githubusercontent.com/683699/164528159-f0e69eaf-b23b-4656-a7d2-b2cbc4bb9e9b.png)

2022-04-22 10:05 UTC, imagico requested changes
This in principle works fine as well, however it introduces brown dot rendering at z17 - which would be a novelty for this style.  Unlike shops where almost all variants start at the same zoom level brown symbols start at very different zoom levels so introducing a dot only rendering at the starting zoom level could seem a bit weird.  Still this could be discussed as a new design idea, however if you want to do so i would suggest to separate that from the bug fix.

As written in #4535 i am not partial to either of the color choices but would like to see a consistent criterion being developed, applied and documented for that.

2022-05-21 17:11 UTC, strongwillow commented
> however it introduces brown dot rendering at z17 - which would be a novelty for this style.

It does not introduce a dot at z17. A purple dot is rendered in the current rendering. See https://www.openstreetmap.org/#map=18/51.42782/5.44144

Car repair shops belong to amenity shop types like `car_wash`. I think it's correct to show them at z17.

2022-06-03 22:53 UTC, jeisenbe requested changes
I believe shop icons should be consistent in one color, so I recommend closing this PR without merging

2022-06-04 01:07 UTC, pnorman commented
I also agree on the purple colour being the better option. Closing in favour of that PR.

2022-06-04 01:07 UTC, closed without merging