Remove support for waterway=riverbank
gravitystorm/openstreetmap-carto pull request #4604
Opened 2022-07-14 16:00 UTC by ZeLonewolf

This PR proposes to remove render support for the tag `waterway=riverbank`, which has fallen to insignificant usage after the tag was:
* Deprecated in a [2011 proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Water_details)
* Marked as deprecated in the iD editor in a [2019 change](https://github.com/openstreetmap/iD/commit/18ea434d021817505638c42de9802aedcf2937ad)
* The subject of a [2021 global tagging campaign](https://wiki.openstreetmap.org/wiki/WikiProject_Waterways/River_modernization) to replace it with `natural=water` + `water=river`
* Removed from the JOSM presets in a [2022 change](https://josm.openstreetmap.de/changeset/18519/josm)

Given the points above, it is no longer appropriate mapper feedback to render this tag.

2022-07-14 16:24 UTC, Eiim commented
I believe that change to project.mml  breaks the parentheses. That line should be `(waterway = 'dock'`, as the closing parenthesis is two lines down.

2022-07-14 16:28 UTC, ZeLonewolf commented
> I believe that change to project.mml breaks the parentheses. That line should be `(waterway = 'dock'`, as the closing parenthesis is two lines down.

Good catch!  Fixed in 3afcca5

2022-07-14 19:19 UTC, imagico commented
The significant drop in use of waterway=riverbank has been largely the result of a centrally organized campaign and massive organized and mechanical editing efforts rather than the result of a genuine grassroots change in tagging consensus in local communities.

I would be strongly against us having any part in that campaign.  However i am also on record for saying that we should maintain our neutrality both ways.  Hence we should support a consensus in tagging even if it became consensus through a centralized campaign suppressing diverging views and practices in local communities.

Because there are quite a few people evidently on watch eliminating re-emerging use of waterway=riverbank it is difficult to gauge how much genuine support the tag still has among local mappers.  A data point i have (as part of the analysis i do for Tagdoc):  Since the beginning of 2021 the tag has been actively added to features by 950 different mappers.  For comparison:  For natural=coastline this number is 1640 mappers, for natural=glacier this is 245 mappers.

So my suggestion at this point is to continue rendering this and maintain our neutrality in what is quite clearly still a dynamic development.

For the record:  The fake news that Ilya's 2011 proposal deprecated waterway=riverbank was demonstrated to be false many years ago.

2022-07-14 19:28 UTC, pnorman requested changes
There are technical issues, as well as considering what to do with the transforms. I would be strongly against removing waterway=riverbank from the transforms. In https://github.com/gravitystorm/openstreetmap-carto/pull/4431/commits/9c4c9c2fdc9af1e6d3fd3f4e336f4b533d63fa0e for the flex backend I went the route of having all waterway tags treated as linestrings except for the few polygon ones.

I am weakly against dropping the rendering of this tag.

2022-07-14 19:46 UTC, Dimitar5555 commented
> Because there are quite a few people evidently on watch eliminating re-emerging use of waterway=riverbank it is difficult to gauge how much genuine support the tag still has among local mappers. A data point i have (as part of the analysis i do for Tagdoc): Since the beginning of 2021 the tag has been actively added to features by 950 different mappers. For comparison: For natural=coastline this number is 1640 mappers, for natural=glacier this is 245 mappers.

Most people don't care about such tags. They use the presets which are suggested by their editing software. The current JOSM version still has it and people will continue to add it until their JOSM gets updated.

2022-07-15 09:49 UTC, imagico commented
> I would be strongly against removing waterway=riverbank from the transforms.

Agreed, even if we - now or at some point in the future - should decide not to render waterway=riverbank any more, we should maintain this level of backwards compatibility for the foreseeable future and also allow derivative styles to easily maintain rendering waterway=riverbank if they for some reason choose to.

2022-07-29 07:28 UTC, pnorman requested changes
I'm basically neutral on the tagging change, but this PR doesn't implement it correctly. Aside from the incorrect change to the transform tests, it ignore an important part of moving tagging of rivers as waterway=riverbank to natural=water + water=river: the rendering of labels.

The style doesn't render names for rivers, because they are already rendered as the centerline. In this PR you need to make that logic work for natural=water water=river, like it does right now for waterway=riverbank. You should also extend the logic to water=canal, water=stream, and other tags for the water covered area of a linear feature.

2022-07-29 07:28 UTC, pnorman commented on scripts/lua/test.lua
> -assert(isarea({waterway = "riverbank"}) == 1, "test failed: river")
This test must remain. It is testing that the area handling for linear features is different than area features in cases where the default for the tag is area, but there are exceptions for some values.

2022-11-29 15:23 UTC, closed without merging

2022-11-29 15:26 UTC, ZeLonewolf commented
Closing PR to work on revisions per comments above.