User friendly improvements to get-external-data.py
gravitystorm/openstreetmap-carto pull request #4609
Opened 2022-07-16 23:46 UTC by Indieberrie

Most important improvement is --no-update option for the script. When set, script will not download newer data to save time if you are constantly importing stuff around.
Add ability to pass options to script in docker via env variables.
Update documentation accordingly to help users better understand how to do it.

Apologies that this took a while.

Also
Fixes #4590 (cache option saving data in place where it was called)

2022-07-17 08:53 UTC, pnorman commented
I'm probably going to use this to load empty shapefiles into the DB as part of CI

2022-07-17 09:04 UTC, Indieberrie commented
I'm glad there is immediate use case!
I forgot to do this, but changes should probably be mentioned in changelog or somewhere else so users know of new functionality.

2022-07-17 09:09 UTC, Indieberrie commented on scripts/get-external-data.py
> +                if "archive" in source and source["archive"]["format"] == "zip":
From here on, changes are mostly identation, I don't know how to make github not display those, but `git diff` has `--ignore-all-space`

2022-07-17 12:55 UTC, Indieberrie commented on scripts/get-external-data.py
> +                if "archive" in source and source["archive"]["format"] == "zip":
Aha, I found how to do it!

2022-07-18 02:01 UTC, pnorman requested changes
Some exception handling issues, as well as a couple of python style issues, but otherwise looks good.

2022-07-18 21:17 UTC, pnorman commented
A re-review was requested, but https://github.com/gravitystorm/openstreetmap-carto/pull/4609/files?w=1#r922931521 is still unaddressed

2022-07-18 22:01 UTC, Indieberrie commented
Do you want me to throw exception there? I hope I explained my reasoning well.
In prior versions it didn't throw exception, and it makes sense to let it download next file, since other files might still be available.

2022-07-18 22:18 UTC, pnorman approved these changes

2022-07-20 21:43 UTC, merged