Add SRID to postgis datasources
gravitystorm/openstreetmap-carto pull request #4651
Opened 2022-08-17 11:56 UTC by StyXman

This way `mapnik` does not have to make expensive queries at XML loading time just to find the layer's projection. This helps a lot shortening feedback loops while modifying the style and viewing the result in f.i. `kosmtik`.

2022-08-18 04:33 UTC, pnorman approved these changes

2022-08-18 09:26 UTC, StyXman commented
Thanks @pnorman but I can't merge myself. Can someone else do it for me? TIA.

2022-08-18 09:53 UTC, imagico requested changes
Fine by me in principle - but if we want to move from `900913` to `3857` we should also change it here:

https://github.com/gravitystorm/openstreetmap-carto/blob/5c0bbb2e011df909f9df3f3efa378d3dc64c70ce/project.mml#L25

2022-08-18 10:05 UTC, StyXman commented
I wonder is the srs's are still needed...

2022-08-18 10:05 UTC, imagico approved these changes
Thanks, looks good now

2022-08-18 10:08 UTC, StyXman commented
Thanks @imagico can you merge it? I don't have the perms :)

2022-08-18 10:11 UTC, imagico commented
> I wonder is the srs's are still needed...

I don't really know.  I remember in the past we had problems with Mapnik performing a round trip conversion Mercator -> geographic -> Mercator because of some mismatch in SRS definitions.

2022-08-19 03:47 UTC, merged

2022-08-19 07:14 UTC, sommerluk commented
That’s really a great speed-up. Thanks a lot!