Remove limited catch-all for access restricted POI styling
gravitystorm/openstreetmap-carto pull request #4717
Opened 2022-10-21 19:07 UTC by imagico

Fixes #4568

Before (`access=foo` is interpreted as restricted):

![access_catchall](https://imagico.de/files/access_catchall.png)

After (`access=foo` is ignored):

![access_nocatchall](https://imagico.de/files/access_nocatchall.png)

This removes the only limited catch-all interpretation on secondary tags in this style (that is the only case where we render all values with a certain key in a special styling variant except for some specific values -  `yes` and `permissive` in this case).  Beyond the problematic mapper feedback this creates a special difficulty when analyzing which tags the style interprets, because it interprets an indefinite number of access values, but not all.

The list of values to be interpreted as restricted is based on the values commonly used on POI features.  See [here](https://taginfo.openstreetmap.org/keys/access?filter=nodes#values) for a more extensive list of values but note that most of these are used on barrier features - which we don't style based on access tagging.

I did not change anything about which POI types get dedicated rendering with a restricted access tag - there is definitely need to re-evaluate that though.  Interpretation of `access=customers` should probably also be considered depending on the type of POI (see #4568)

2022-10-22 16:27 UTC, sommerluk requested changes
I haven’t looked yet at the details of this PR, but in general I’m in favour.

I would suggest to use `AS int_access` instead of `AS access`, as we do yet (partially) with other query data columns that are the result of an SQL calculation.

2022-10-22 18:21 UTC, imagico commented
Done, yes, that we should do more diligently to avoid confusion when people are reading the code.

2022-10-23 20:16 UTC, sommerluk reviewed
A rather funny, subtle rendering change are the airports for “customers”. Before this PR, only `private` is considered like `restricted` for airports. After this PR, additionally `delivery` (0 cases in OSM), `permit` (1 case in OSM), `no` (37 cases in OSM) and `customers` (1 case in OSM) are also considered like `restricted`. `delivery` does not occur in the database. For `permit` and `no`, the change is for good. The case with `customers` is https://www.openstreetmap.org/node/768506105 so before this PR, symbol and name render from z11 on, after this PR, the icon starts rendering at z12 and the name at z13. It does not make sense to tag an airport with `access=customers` because all people visiting the airport are usually considered “customers” (just like it makes sense to tag the parking of a supermarket with `access=customers`, but it doesn’t make sense to apply this tag to the supermarket itself.). So this is probably a tagging error.

2022-10-23 20:17 UTC, sommerluk approved these changes

2022-10-29 18:32 UTC, imagico commented
Yes, we could think about having a different logic for airports.  Since here the access tag is used differently in terms of styling it would not be too confusing for the map user.  

I have never been particularly fond of using access tagging for importance rating of airports because it is not widely used and most small, private airfields have no access tagging.  There are only about 770 combinations of `aeroway=aerodrome` with `access=private` while there are more than twice as many just for combinations of `aeroway=aerodrome` with `military=airfield` - most of which are non-public.  Not to mention the principal ambiguity of access tagging referring to access from the air vs. access on the ground.  So a better solution would probably be not to interpret access tagging on `aeroway=aerodrome`.

2022-10-29 18:33 UTC, merged