Fix for #3504
gravitystorm/openstreetmap-carto pull request #4766
Opened 2023-01-09 20:15 UTC by mboeringa

Remove "virtual" border lines on the antimeridian by excluding all features tagged as closure segment.

Fixes #3504

Changes proposed in this pull request:
Remove virtual borders on the antimeridian by making use of the enhanced capabilities of osm2pgsql 'flex output' and associated LUA configuration.

Test rendering with links to the example places:

Before
#3504 (comment)
After
#3504 (comment)

2023-01-09 20:19 UTC, mboeringa commented
@pnorman , could you have a look at this? It fixes the virtual border rendering on the antimeridian using the new capabilities of flex output.

2023-01-09 22:02 UTC, pnorman commented
Can you add appropriate data to test_relations in the tests?

2023-01-10 17:53 UTC, mboeringa commented
> Can you add appropriate data to test_relations in the tests?

@pnorman , done in https://github.com/gravitystorm/openstreetmap-carto/pull/4766/commits/aa9b75a8927dde7eaf3e5aedca5aee74d76bbe7e.

Bear with me, this is the first time I ever dealt with this kind of test data and test framework, but I think the logic should be right now.

2023-02-25 05:17 UTC, pnorman requested changes

2023-02-25 05:17 UTC, pnorman commented on scripts/lua/test.lua
> +                  {type = 'w', ref = 9, role = "outer"}
This line is missing a `,` at the end of it.

2023-02-25 05:39 UTC, merged

2023-02-25 05:39 UTC, pnorman commented
I did the fixups and merged