Add `natural=peninsula` labels
gravitystorm/openstreetmap-carto pull request #4778
Opened 2023-02-21 16:21 UTC by quincylvania

Fixes #3897. [`natural=peninsula`](https://wiki.openstreetmap.org/wiki/Tag:natural=peninsula) was approved in 2019 and has grown in usage since then. The tag is used for various large landmasses that often appear on maps. For example: the [Arabian](https://www.openstreetmap.org/relation/5631846), [Kamchatka](https://www.openstreetmap.org/relation/7752000), [Delmarva](https://www.openstreetmap.org/relation/15511019), [Jutland](https://www.openstreetmap.org/relation/11734020), and [Tiburon](https://www.openstreetmap.org/relation/15514201) Peninsulas. I this we can just apply the styling for `place=island` given their similarities as landforms surrounded by water.

I didn't yet spin up a development instance of this project for testing, but I can try to do so later.

2023-02-21 18:06 UTC, imagico commented
Thanks for the pull request.

`natural=peninsula` has 1791 uses, about 2/3 of these are on nodes.

This change would render them the same way we had rendered `natural=bay` from 2018 (#3144) to 2022 (#3750) which led to a massive incentive for mappers to draw non-verifiable and hard to maintain labeling polygons for those (see #4546).

So lets not make the same mistake twice.

I would be fine with rendering `natural=peninsula` like `place=locality` and this way support mappers in using the more specific tag, possibly even one or two zoom levels earlier (but that would need to be tested in low latitude areas with many small peninsulas).  This is also what #3897 suggests.

2023-02-22 01:22 UTC, quincylvania commented
> I would be fine with rendering natural=peninsula like place=locality and this way support mappers in using the more specific tag, possibly even one or two zoom levels earlier

Okay, this sounds fine. I'd just like to see these supported in whatever way makes the most sense.

2023-03-13 18:11 UTC, imagico requested changes
Design wise this is fine - but we don't want to select the starting zoom level based on way_area due to the bad experience with that in the past with other features.  If you have the time i would encourage you to test if starting peninsula labels at z15 or even z14 would work - we start bays at z14, though of course bays are on water so their labels are less likely to conflict with other labels.

In the long terms we could - both for peninsulas and for bays - consider using data preprocessing for meaningful importance rating and label placement independent of how the features are mapped.  See past discussion in #3634 and also #3720.  Since this would be a somewhat more substantial project unlikely to be completed by volunteers and not tied specifically to OSM-Carto it would be a good candidate for anyone looking into sponsoring meaningful work in support of better quality in OSM community maps.

2025-02-05 16:23 UTC, quincylvania commented on style/amenity-points.mss
> +  [feature = 'natural_peninsula'][zoom >= 10][way_pixels > 3000],
Okay, I dropped the low zoom label

2025-02-07 18:15 UTC, dch0ph commented
I do think that starting zoom will need to be 14 like `natural=bay` for these labels to be in any way useful. `place=locality` starting at Z16 makes sense since these are very local labels. 

Although I agree entirely that allowing a starting zoom based on area leads to bad mapping, I worry that `natural=peninsula` can vary so much in size (think Arabian Peninsula) that starting labelling even at Z14 will not result in very useful labels.

2025-02-09 17:58 UTC, imagico requested changes
Looks fine to me now, thanks for keeping working on this.

There are two now unnecessary changes in the low zoom layer that should be removed - see inline comments.

As far as the starting zoom level is concerned - @dch0ph has a point that z14 might be more consistent with the other features we render with labels - `natural=bay` but also `natural=cape`.  I had a quick look over the data and there are some cases where z14 would be too early to show a label - but these are not that frequent.  Which could be partly because peninsula mapping is so far concentrated on higher latitudes.

Anyway - i would be fine with adding this as is but i would also fine with starting at z14 already (and accepting that a revision of the starting zoom level might be necessary if this starts being used in high density in the future - as we have done for other features in the past).

2025-02-09 17:58 UTC, imagico commented on project.mml
> +              'natural_' || CASE WHEN "natural" IN ('wood', 'glacier', 'sand', 'scree', 'shingle', 'bare_rock', 'water', 'peninsula') THEN "natural" END,
This change does not have a function any more if we render peninsulas starting z16 (or z14) since the low zoom text layer ends at z9.

2025-02-09 17:58 UTC, imagico commented on project.mml
> +              OR "natural" IN ('wood', 'glacier', 'sand', 'scree', 'shingle', 'bare_rock', 'water', 'peninsula')
see above

2025-02-10 14:27 UTC, quincylvania commented
Thanks for the feedback. I'm fine merging as-is and then considering revisions later.

2025-02-10 18:08 UTC, merged

2025-02-10 18:08 UTC, imagico commented
Label design of these is further discussed in #5062