Restored rendering for railway=platform + covered=yes
gravitystorm/openstreetmap-carto pull request #4797
Opened 2023-03-27 21:07 UTC by map-per

Fixes #4008

Changes proposed in this pull request:
- Restored rendering for railway=platform + covered=yes

Test rendering with links to the example places:
https://www.openstreetmap.org/way/160042477 (left before, right after)
![platform19](https://user-images.githubusercontent.com/79519062/228065901-42d7ceeb-1fbf-421a-bfa4-46d4eb72bccb.png)
![platform18](https://user-images.githubusercontent.com/79519062/228066561-6155aa0a-8094-4f6e-b814-efaf2f1ed090.png)

2023-05-07 11:47 UTC, map-per commented
Is there anything I can do to move this pullrequest forward?

2023-05-28 16:19 UTC, map-per commented
@pnorman & @imagico: Is @jeisenbe still active and doing reviews?

2023-06-30 16:53 UTC, map-per commented
Can someone please review this (@pnorman & @imagico)

2023-07-02 18:59 UTC, imagico requested changes
I am sorry it took us so long to review this.

The main reason is probably that the style is quite a mess w.r.t. the whole subject of multilayered transportation infrastructure complexes and none of us seems very keen to touch that.

As @jeisenbe commented in https://github.com/gravitystorm/openstreetmap-carto/issues/4008#issuecomment-578416338 the change hiding `railway=platform` + `covered=yes` was an ad-hoc change made without consensus on a bigger strategy.

I would be fine in principle with restoring specifically display of `railway=platform` + `covered=yes`, even if that is kind of another ad-hoc change on top of this because it indeed seems that hiding based on this tag specifically is highly problematic for mapper feedback.

However, i think this should fix at least the main inconsistencies in selective hiding of features and not introduce any new inconsistencies.  Here is how current master renders the various variants:

![master](https://imagico.de/files/platform_covered_master.png)

And here how this change affects this:

![this](https://imagico.de/files/platform_covered_changed.png)

The inconsistencies between linear way and polygon mapping should be resolved.  I also would prefer it if we would treat `highway=platform` and `railway=platform` identically - but i am not tied to that.

Beyond that - we really need to develop an overall strategy how to handle multilevel transportation complexes and mapping of multi-level and underground features in those.  How such a strategy can look like will depend on how much additional complexity we are willing to accept to accommodate that in the style and i am not sure if we are able to achieve consensus on that.

2023-07-12 16:52 UTC, map-per commented
Thanks for the review

2023-08-15 18:51 UTC, map-per commented
Ok, resolved the inconsistencies for `railway=platform`. Now linear platforms with `covered=yes` are displayed and platforms with `location=underground` are hidden.

### Examples

Platform with `covered=yes` and without `tunnel=yes` or `location=underground` is shown (https://www.openstreetmap.org/way/166482810)
![platform1](https://github.com/gravitystorm/openstreetmap-carto/assets/79519062/705ed0cc-679d-4dbc-a6dd-392908be78aa)

Platform with `location=underground` is not shown (https://www.openstreetmap.org/way/432808388)
![Bildschirmfoto_2023-08-15_20-27-53](https://github.com/gravitystorm/openstreetmap-carto/assets/79519062/2d8285ce-a8f3-4452-b135-fef3b24a6a12)

Platform with `location=underground` and `tunnel=yes` not shown (https://www.openstreetmap.org/way/432808388)
![Bildschirmfoto_2023-08-15_20-29-52](https://github.com/gravitystorm/openstreetmap-carto/assets/79519062/5bd1872e-3a32-4e7c-a010-21ab6dc1cac8)

2023-10-06 17:44 UTC, imagico approved these changes
Works as intended now:

![this](https://imagico.de/files/platform_covered_changed2.png)

And as said above i see this as a definitive improvement.

2023-10-14 15:03 UTC, map-per commented
Great, can you merge it? Or are you waiting for others to review the PR as well?

2023-10-14 16:32 UTC, merged

2023-10-14 18:52 UTC, map-per commented
🎉