Use common Single Quotes for Strings
gravitystorm/openstreetmap-carto pull request #4939
Opened 2024-03-06 06:37 UTC by MaikBusch78

Fixes NO issue, just cosmetic change

Changes proposed in this pull request:
- Use single quoting for String constants

Test rendering with links to the example places:
- Rendering should not be influenced by this cosmetic change

2024-03-06 12:53 UTC, pnorman commented
> Rendering should not be influenced by this cosmetic change

Have you tested this?

2024-03-06 15:14 UTC, MaikBusch78 commented
> > Rendering should not be influenced by this cosmetic change
> 
> Have you tested this?

No

2024-03-06 22:30 UTC, imagico requested changes
This needs testing - yes, this kind of change *should not*  affect rendering - but we know from experience that Carto can be fairly particular when interpreting code - so we should not make assumptions here.

Regarding the idea of establishing stricter conventions on MSS coding - i am not opposed, but i think this should be documented in our [coding guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md) then.

2024-03-07 16:30 UTC, MaikBusch78 commented
Ok, i have tested it now by calling `carto project.mml > project.xml.{number}` on the original and on the changed quotes for string values version. Changing only the quotes from double to single the result is exactly the same (md5sum). To be sure that my changes have been reflected in the result i also tested to change the values. Changing entrance values from `main` to `mainx` resulted in many many changes in the xml. Changing leaf_type from `leafless` to `leaflessx` resulted in only a single line change.
From my understanding how the style is used, i believe that this kind of test is good enough.

2024-03-07 16:31 UTC, MaikBusch78 commented
I have also updated the coding guidelines.

2024-03-07 16:47 UTC, imagico approved these changes

2024-04-02 08:18 UTC, MaikBusch78 commented
@imagico I have seen now, you are also a maintainer. So i may ask you, what is left to do to make this PR merged?

2024-04-02 18:16 UTC, merged